name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install server dependencies
        working-directory: ./
        run: yarn install

      - name: Install client dependencies
        working-directory: ./client
        run: yarn install

      - name: Lint client code
        working-directory: ./client
        run: yarn lint

      - name: Run server tests (Jest)
        working-directory: ./
        run: yarn test --ci

      - name: Run client tests (React)
        working-directory: ./client
        run: yarn test --ci --watchAll=false

      - name: Build client
        working-directory: ./client
        run: yarn build
